#!/bin/bash
usb
cd /home/$USER
mkdir archlive 2> /dev/null
cd archlive
mkdir install_dir
#sudo rm -r work
sudo mkarchiso -v -o /home/$USER/archlive/out -w /home/$USER/archlive/work -D /home/$USER/archlive/install_dir -r /home/$USER/archlive

#run_archiso -u -i /home/$USER/archlive/out/archlinux-baseline-2023.09.11-x86_64.iso
