#!/bin/bash
sudo pacman -S --needed rsync reflector
clear
sudo reflector --verbose -c 'SE,NO,FI,DK' --sort rate --protocol https,http --completion-percent 100 -a 2 --save /etc/pacman.d/mirrorlist.fast
