#!/bin/bash
sudo pacman -S discover
sudo pacman -S appstream-qt archlinux-appstream-data discount kidletime kirigami2 knewstuff kuserfeedback purpose qt5-graphicaleffects qt5-webview flatpak fwupd packagekit-qt5 extra-cmake-modules plasma-framework
